version: '3.5'

services:
  pnyx_langserve:
    container_name: pocket_network_langserve
    image: docker.io/library/pocket_network_langserve:latest
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POCKET_NEWTWORK_ETH_URL=${POCKET_NEWTWORK_ETH_URL}
    ports:
     - "8080:8080"